theme: jekyll-theme-minimal
title: sjamesadkins Homepage
description: Bookmark this page to view my resume and keep an eye on my project updates!
linkedin: LinkedIn Profile: https://www.linkedin.com/in/adkins-mba/
